# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.9
    hooks:
      # Run the linter.
      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        language: python
      # Run the formatter.
      - id: ruff-format
        name: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        language: python