# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
      - id: ruff
        name: Ruff Linter
        description: "Run 'ruff' for extremely fast Python linting"
        language: python
      - id: ruff-format
        name: Ruff Code Format
        description: "Run 'ruff format' for extremely fast Python formatting"
        language: python
  - repo: https://github.com/christophmeissner/pytest-pre-commit
    rev: 1.0.0
    hooks:
    - id: pytest
      name: Pytest
      pass_filenames: false
      always_run: true